const _ids = {
   green: {
      advertisement: '6328c4fd9ef93a12f6129871',
      agriculture: '6328c4fd9ef93a12f6129873',
   },
}
const green_advertisement = [
   { word: 'provide', meaning: '', parent: _ids.green.agriculture },
   { word: 'product', meaning: 'منتج', parent: _ids.green.agriculture },
   { word: 'posted', meaning: 'نشر', parent: _ids.green.agriculture },
   {
      word: 'quality',
      meaning: 'تجاري، اعلان تجاري',
      parent: _ids.green.agriculture,
   },
   {
      word: 'commercial',
      meaning: 'عرض، إظهار',
      parent: _ids.green.agriculture,
   },
   { word: 'display', meaning: 'عرض، اظهار', parent: _ids.green.agriculture },
   { word: 'marketed', meaning: 'يُسوِّق', parent: _ids.green.agriculture },
   {
      word: 'promote',
      meaning: 'يروج، يشجّع، يطوّر',
      parent: _ids.green.agriculture,
   },
   {
      word: 'communicate',
      meaning: 'ينقل، يتواصل',
      parent: _ids.green.agriculture,
   },
   { word: 'media', meaning: 'وسائل الاعلام', parent: _ids.green.agriculture },
   { word: 'version', meaning: 'اصدار، صيغة', parent: _ids.green.agriculture },
   { word: 'editor', meaning: 'محرّر', parent: _ids.green.agriculture },
   { word: 'exposed', meaning: 'كَشَف', parent: _ids.green.agriculture },
   { word: 'guide', meaning: 'مرشد، دليل', parent: _ids.green.agriculture },
   { word: 'persuade', meaning: 'يقنع', parent: _ids.green.agriculture },
   { word: 'logo', meaning: 'شعار', parent: _ids.green.agriculture },
   { word: 'aim', meaning: 'هدف', parent: _ids.green.agriculture },
   { word: 'campaign', meaning: 'حملة', parent: _ids.green.agriculture },
   { word: 'phrase', meaning: 'عبارة', parent: _ids.green.agriculture },
   {
      word: 'granted',
      meaning: 'اكيد، موهوب، ممنوح',
      parent: _ids.green.agriculture,
   },
   {
      word: 'trademark',
      meaning: 'علامة تجارية',
      parent: _ids.green.agriculture,
   },
   {
      word: 'exclusive',
      meaning: 'حصري، باستثناء، مقصور',
      parent: _ids.green.agriculture,
   },
   { word: 'publisher', meaning: 'الناشر', parent: _ids.green.agriculture },
   { word: 'announce', meaning: 'يعلن', parent: _ids.green.agriculture },
   {
      word: 'revision',
      meaning: 'مراجعة، تنقيح',
      parent: _ids.green.agriculture,
   },
   {
      word: 'proclaim',
      meaning: 'يعلن، نشر، صرّح',
      parent: _ids.green.agriculture,
   },
]

const green_agriculture = [
   { word: 'flower', meaning: 'زهرة', parent: _ids.green.agriculture },
   { word: 'season', meaning: 'موسم / يبهّر', parent: _ids.green.agriculture },
   {
      word: 'field',
      meaning: 'حقل / ميدان /مجال',
      parent: _ids.green.agriculture,
   },
   { word: 'crop', meaning: 'يقصّ / محصول', parent: _ids.green.agriculture },
   {
      word: 'grains',
      meaning: 'حبوب / بقوليات',
      parent: _ids.green.agriculture,
   },
   {
      word: 'absorb',
      meaning: 'يمتصّ / يستوعب',
      parent: _ids.green.agriculture,
   },
   { word: 'seed', meaning: 'بذرة', parent: _ids.green.agriculture },
   { word: 'drought', meaning: 'جفاف / قحط', parent: _ids.green.agriculture },
   { word: 'abundant', meaning: 'وافر', parent: _ids.green.agriculture },
   {
      word: 'yield',
      meaning: 'يخضع / يستسلم / محصول / دخل',
      parent: _ids.green.agriculture,
   },
   {
      word: 'cultivate',
      meaning: 'يزرع / يفلح / يحرث',
      parent: _ids.green.agriculture,
   },
   { word: 'soil', meaning: 'تربة', parent: _ids.green.agriculture },
   {
      word: 'tract',
      meaning: 'قطعة ارض / مسالك',
      parent: _ids.green.agriculture,
   },
   { word: 'genus', meaning: 'جنس / صنف', parent: _ids.green.agriculture },
]

const orange_advertisement = {
   list: {
      name: 'Advertisement',
      parent: 'Epsos Orange Dictionary',
      imgSrc: 'advertisement.jpg',
   },
   words: [
      { word: 'advertisement', meaning: 'اعلان، دعاية' },
      { word: 'journalist', meaning: 'صحافيّ' },
      { word: 'sponsored', meaning: 'مموّل' },
      { word: 'statement', meaning: 'بيان، تصريح' },
      { word: 'distribution', meaning: 'توزيع' },
      { word: 'merchandise', meaning: 'بضائع' },
      { word: 'label', meaning: 'بطاقة، ملصق' },
      { word: 'misleading', meaning: 'مضلل' },
      { word: 'press', meaning: 'صحافة، ضَغَطَ' },
      { word: 'scandal', meaning: 'فضيحة' },
      { word: 'taunt', meaning: 'تهكّم، سخرية، عالي' },
      { word: 'subscription', meaning: 'اشتراك' },
   ],
}
const orange_agriculture = {
   list: {
      name: 'Agriculture',
      parent: 'Epsos Orange Dictionary',
      imgSrc: 'agriculture.jpg',
   },
   words: [
      { word: 'blossom', meaning: 'يزدهر' },
      { word: 'cluster', meaning: 'عنقود' },
      { word: 'crease', meaning: 'تجعّد، غصن' },
      { word: 'ferment', meaning: 'تخمر' },
      { word: 'immerse', meaning: 'يغمر' },
      { word: 'meadow', meaning: 'مرج' },
      { word: 'orchard', meaning: 'بستان' },
      { word: 'precipitation', meaning: 'ترسّب' },
      { word: 'shortage', meaning: 'نقص' },
      { word: 'fertile', meaning: 'خصب' },
      { word: 'acre', meaning: 'فدان' },
      { word: 'harvest', meaning: 'حصاد' },
      { word: 'hollow', meaning: 'اجوف' },
      { word: 'reap', meaning: 'يحصد' },
      { word: 'trim', meaning: 'يقلّم' },
      { word: 'wheat', meaning: 'قمح' },
      { word: 'arduous', meaning: 'شاق، مجهد' },
      { word: 'core', meaning: 'نواة، جوهر، لُب' },
      { word: 'irrigate', meaning: 'يروي، يسقي' },
      { word: 'squash', meaning: 'قرع، كوسا / سحق، هرس' },
      { word: 'stem', meaning: 'ايقاف / جذع' },
      { word: 'synthesize', meaning: 'تركيب' },
      { word: 'thrive', meaning: 'يزدهر، ينمو' },
      { word: 'trunk', meaning: 'جذع، جسم' },
      { word: 'vine', meaning: 'نبات معترش' },
   ],
}
const green_art_literature = {
   list: {
      name: 'Art&Literature',
      parent: 'Epsos Green Dictionary',
      imgSrc: 'art&literature.jpeg',
   },
   words: [
      { word: 'show', meaning: 'عرض، مسرحية' },
      { word: 'infer', meaning: 'استنتج' },
      { word: 'novel', meaning: 'رواية' },
      { word: 'refer to', meaning: 'يشير الى' },
      { word: 'author', meaning: 'مؤلف' },
      { word: 'poetry', meaning: 'شعر' },
      { word: 'establish', meaning: 'إنشاء، يقيم' },
      { word: 'letter', meaning: 'حرف، رسالة' },
      { word: 'literary', meaning: 'ادبي' },
      { word: 'certain', meaning: 'مؤكَّد، واثق، معين' },
      { word: 'compose', meaning: 'مؤلف موسيقى، ملحن، يشكل' },
      { word: 'library', meaning: 'مكتبة' },
      { word: 'portrait', meaning: 'صورة او رسمة (بالعادة لوجه)' },
      { word: 'record', meaning: 'يسجّل، يدوّن' },
      { word: 'note', meaning: 'ملاحظة، نوتة' },
      { word: 'poet', meaning: 'شاعر' },
      { word: 'perform', meaning: 'ينفّذ' },
      { word: 'express', meaning: 'تعبير، سريع، عبر' },
      { word: 'pattern', meaning: 'نمط، نموذج، اسلوب، عينة' },
      { word: 'critic', meaning: 'ناقد' },
      { word: 'inspire', meaning: 'يُلهِم' },
      { word: 'interpret', meaning: 'يفسّر' },
      { word: 'symbol', meaning: 'حرف، رمز' },
      { word: 'valuable', meaning: 'قيّم' },
      { word: 'attribute', meaning: 'ينسب، ميزة، رمز' },
      { word: 'coin', meaning: 'عملة، صياغة لغوية' },
      { word: 'distinct', meaning: 'مميّز، بارز، مختلف' },
      { word: 'punctuation', meaning: 'علامات رقمية' },
      { word: 'display', meaning: 'عرض، اظهار' },
      { word: 'reference', meaning: 'مرجع' },
      { word: 'legend', meaning: 'خرافة، اسطورة' },
      { word: 'character', meaning: 'شخصية' },
      { word: 'content', meaning: 'المحتوى، فَحوى' },
      { word: 'convey', meaning: 'نقل، أبلغ' },
      { word: 'title', meaning: 'عنوان' },
      { word: 'depict', meaning: 'يصف' },
      { word: 'spelling', meaning: 'تهجو' },
      { word: 'interpretation', meaning: 'تفسير، تأويل' },
      { word: 'composition', meaning: 'تراكيب، مؤلفات' },
      { word: 'publication', meaning: 'النشر' },
      { word: 'speech', meaning: 'خطاب' },
      { word: 'artifact', meaning: 'قطعة أثريّة' },
      { word: 'background', meaning: 'خلفية' },
      { word: 'carve', meaning: 'ينقش، ينحت' },
      { word: 'impressive', meaning: 'مثير للاعجاب' },
      { word: 'reveal', meaning: 'كشف' },
      { word: 'sculptor', meaning: 'نحّات' },
      { word: 'signals', meaning: 'إشارات' },
      { word: 'admire', meaning: 'معجب، يقدّر' },
      { word: 'editor', meaning: 'محرر' },
      { word: 'fabric', meaning: 'قماش' },
      { word: 'outstanding', meaning: 'امتياز' },
      { word: 'volume', meaning: 'حجم، شدّة الصوت، كتاب' },
      { word: 'verse', meaning: 'بيت شعر، آية' },
      { word: 'sculpture', meaning: 'ينحت، تِمْثال' },
      { word: 'accuracy', meaning: 'دقة' },
      { word: 'theatre', meaning: 'مسرح' },
      { word: 'playwrights', meaning: 'الكتاب المسرحيون' },
      { word: 'pose', meaning: 'وضعية، يشكّل' },
      { word: 'stage', meaning: 'المسرح، مرحلة' },
      { word: 'summarize', meaning: 'تلخيص' },
      { word: 'pronunciation', meaning: 'لفظ' },
      { word: 'concert', meaning: 'حفلة موسيقية' },
      { word: 'director', meaning: 'مخرج، مدير' },
      { word: 'exaggerate', meaning: 'يبالغ' },
      { word: 'inspiration', meaning: 'وحي، الهام' },
      { word: 'introduction', meaning: 'مقدمة' },
      { word: 'passage', meaning: 'ممرّ، نصّ' },
      { word: 'saying', meaning: 'قول' },
      { word: 'tape', meaning: 'شريط، شريط تسجيل، ڤيديو' },
      { word: 'dye', meaning: 'صبغة' },
      { word: 'abbreviate', meaning: 'اختصر' },
      { word: 'calligrapher', meaning: 'خطاط' },
      { word: 'curtain', meaning: 'ستار' },
      { word: 'edition', meaning: 'إصدار' },
   ],
}

module.exports = {
   green_agriculture,
   green_advertisement,
   green_art_literature,
   orange_advertisement,
   orange_agriculture,
}
